Feature/3 dao
ncedu-tlt/2019-ux-sea-battle pull request #12
Opened 2020-03-27 18:24 UTC by Danilov-Andrey

2020-03-28 09:43 UTC, ocassio commented
Для начала сделай rebase на последний мастер и разрули все конфликты.

2020-03-29 11:55 UTC, ocassio requested changes

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/db.module.ts
> +import { FriendStatusDAO } from "./domain/friendStatus.dao";
Для файлов используем kebab-case.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/achievement.dao.ts
> +    @Column({ nullable: false })
Nullable по умолчанию равен false. Не надо добавлять лишний шум в код.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/ban.dao.ts
> +    updateDate(): void {
1. Почему метод, который выполняется перед добавлением, называется `updateDate`?
2. Почему метод расположен где-то между полями?
3. Что будет, если я явно задам дату на сущности?

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/ban.dao.ts
> +        eager: true,
Всегда ли нам будет нужна инфа о том, что кем именно был забанен пользователь? Мне кажется, что в большинстве случаев нам это будет неинтересно.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/ban.dao.ts
> +        eager: true,
Аналогично.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/ban.dao.ts
> +    type: BanTypeDAO;
Для таких вещей проще использовать enum.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/friend.dao.ts
> +export class FriendDAO {
Эта сущность вообще не нужна, это связь многие ко многим, ORM сам сделает промежуточную таблицу.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/friendStatus.dao.ts
> +export class FriendStatusDAO {
Можно заменить на enum.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/game.dao.ts
> +    gameMode: Promise<GameModeDAO>;
Снова enum.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/game.dao.ts
> +    gameStatus: Promise<GameStatusDAO>;
enum

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/game.dao.ts
> +    @Column({ name: "created_at", type: "timestamp" }) createdAt: Date;
Куда форматирование поплыло?

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/participant.dao.ts
> +    @PrimaryGeneratedColumn() id: number;
Снова форматирование.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/participant.dao.ts
> +    user: Promise<UserDAO>;
Почему один к одному? Один игрок может быть участником только одной игры?

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/participant.dao.ts
> +    game: Promise<GameDAO>;
В одной игре может быть только один участник?

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/post.dao.ts
> +    authorId: Promise<UserDAO>;
`author`, а не `authorId`.

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/report.dao.ts
> +    processedBy: Promise<UserDAO>;
1. Почему один к одному?
2. Почему `nullable: false`?

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/report.dao.ts
> +    createdBy: Promise<UserDAO>;
Один к одному?

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/report.dao.ts
> +    target: Promise<UserDAO>;
Один к одному?

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/report.dao.ts
> +    status: Promise<ReportDAO>;
Короче проверь все связи один к одному :)

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/reportStatus.dao.ts
> +export class ReportStatusDAO {
enum

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/role.dao.ts
> +export class RoleDAO {
enum

2020-03-29 11:55 UTC, ocassio commented on server/modules/db/domain/shipPreset.dao.ts
> +export class ShipPresetDAO {
Имя не нужно?

2020-03-29 12:43 UTC, Danilov-Andrey commented on server/modules/db/domain/friend.dao.ts
> +export class FriendDAO {
Я забыл добавить в сущность статус запроса в друзья.

2020-03-30 07:13 UTC, ocassio requested changes
Проставь  явно имена табличкам, а то они сейчас выглядят как `user_dao`.

2020-03-30 07:13 UTC, ocassio commented on server/modules/db/domain/ban.dao.ts
> +    removedBy: Promise<UserDAO>;
nullable

2020-03-30 07:13 UTC, ocassio commented on server/modules/db/domain/game.dao.ts
> +    roomName: string;
А если это был автоподбор соперника?

2020-03-30 07:13 UTC, ocassio commented on server/modules/db/domain/post-like.dao.ts
> +export class PostLikeDAO {
Можно заменить связью многие ко многим.

2020-03-30 07:13 UTC, ocassio commented on server/modules/db/domain/ship-preset.dao.ts
> +export class ShipPresetDAO {
Думаю, стоит еще режимом ограничить.

2020-03-30 07:13 UTC, ocassio commented on server/modules/db/domain/tag.dao.ts
> +    tag: string;
Лучше name.

2020-03-30 07:13 UTC, ocassio commented on server/modules/db/domain/user.dao.ts
>      email: string;
unique

2020-03-30 07:13 UTC, ocassio commented on server/modules/db/domain/user.dao.ts
> +    isDnd: boolean;
Может это со статусом объединить?

2020-03-31 16:36 UTC, ocassio approved these changes

2020-03-31 16:36 UTC, merged