9 // [Регистрация] Отсутствуют проверки на наличие значения у поля
ncedu-tlt/2019-ux-sea-battle pull request #13
Opened 2020-03-28 10:45 UTC by awpogodin

Fixed 9, 10, 11 issues

2020-03-29 11:29 UTC, ocassio requested changes

2020-03-29 11:29 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +        return;
Зачем тебе тут вообще return?

2020-03-29 11:29 UTC, ocassio commented on server/modules/auth/auth.service.ts
>      public async register(registerDTO: RegisterRequestDTO): Promise<any> {
Кстати, а почему до сих пор any?

2020-03-30 06:45 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +            (await this.usersService.findByNickname(registerDTO.nickname));
Вот это лучше одним запросом сделать.

2020-03-30 11:48 UTC, awpogodin commented on server/modules/auth/auth.service.ts
> +            (await this.usersService.findByNickname(registerDTO.nickname));
Один запрос в сервис? Или к бд?

2020-03-30 14:49 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +            (await this.usersService.findByNickname(registerDTO.nickname));
В БД.

2020-03-31 05:58 UTC, ocassio commented
![image](https://user-images.githubusercontent.com/6851647/77991951-1ff80e80-7336-11ea-95dd-eff4ba3d72ab.png)

2020-04-01 05:56 UTC, ocassio approved these changes

2020-04-01 05:56 UTC, merged