feature/22-search-for-rivals
ncedu-tlt/2019-ux-sea-battle pull request #25
Opened 2020-05-14 15:16 UTC by fanikuk

Closes #22

2020-05-16 10:12 UTC, ocassio requested changes

2020-05-16 10:12 UTC, ocassio commented on server/modules/db/domain/game-mode.enum.ts
> +    SALVO_P = "salvo_m"
Давай лишние пока все-таки уберем)

2020-05-16 10:12 UTC, ocassio commented on server/modules/game/game.module.ts
> +    controllers: []
Controllers можно не обозначать, раз ничего не регистрируем.

2020-05-16 10:12 UTC, ocassio commented on server/modules/game/game.service.ts
> +        const game = {
Тип в таких случаях нужно прописывать явно, иначе проверок нет.

2020-05-16 10:12 UTC, ocassio commented on server/modules/game/game.service.ts
> +        const game = {
А если мы захотим создать публичную игру?

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/classic.service.ts
> +                ([key, value]) => value === GameModeEnum.CLASSIC
Тут правильней будет не отключать правило, а либо не использовать деструктуризацию, либо опустить key, чтобы получилось что-то вроде:
```js
[, value] => value === GameModeEnum.CLASSIC
```

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/classic.service.ts
> +    async classicModeSearch(
1. Стоить сделать интерфейс, который будут реализовывать все сервисы для поиска игры, со стандартизированным API.
2. `socketToRivalsMapping` - судя по коду там вообще маппинг userId на режим :)
3. Мне кажется, что отсевом игроков по режиму не должен заниматься сам сервис, их можно разбивать на группы прям в момент постановки в очередь. Иначе сильный оверхед выходит.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/classic.service.ts
> +    ): Promise<RoomDto> {
Если может ничего не вернуться, то было бы неплохо уточнить это в типе.

2020-05-16 10:12 UTC, ocassio commented on server/modules/game/game.service.ts
> +        const game = {
У нас игроки к игре не привязываются?

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/classic.service.ts
> +        if (playersForClassicMode.size === 2) {
А если их больше?)

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +@UseGuards(WsAuthGuard)
А guard то в итоге нужен разве?

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +@WebSocketGateway({ namespace: "rivals" })
Лучше game-search или что-то в этом духе.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +            case GameModeEnum.CLASSIC:
Отличный сценарий для фабрики)

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +    private room: RoomDto;
Это явно должна быть локальная переменная. Она используется только в рамках одного выполнения функции. При текущем же подходе много одновременных подключений начнут ломать логику друг друга.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +            socket.emit("connection", "401");
Это стоит тоже в сервис убрать, будет присутствовать во всех остальных контроллерах.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +            this.server.to(this.room.id).emit("search", this.room.id);
Тут стоит просто выкинуть сообщение, что игра найдена. А они потом сами подключаться к другому гейтвею и будут распределены по комнатам.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/strategy/jwt-ws.strategy.ts
> +export class JwtWsStrategy extends PassportStrategy(
Стратегия нам не нужна при текущем подходе, если я все правильно понимаю.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/ws-exception-handling.service.ts
> +                "tokenSecretKey"
Секрет то из конфига забирать надо.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/ws-exception-handling.service.ts
> +    async tokenCheck(socket: Socket): Promise<UserDTO> {
Сервис для внутренней логики, тут не стоит оперировать DTO.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/ws-exception-handling.service.ts
> +export class WsExceptionHandlingService {
Лучше что-нибудь в духе WsAuthService, и перенести его в AuthModule, он много где нужен будет.

2020-05-16 10:12 UTC, ocassio commented on server/modules/search-for-rivals/ws-exception-handling.service.ts
> +            return undefined;
Советую залогировать на debug уровне, в дальнейшем избавит от большого количества головной боли.

2020-05-16 10:12 UTC, ocassio commented on server/guards/ws-auth.guard.ts
> +export class WsAuthGuard extends AuthGuard("websocketStrategy") {
А он нам еще нужен?

2020-05-25 10:51 UTC, ocassio requested changes
Ну и сугубо мое мнение, matchmaking звучит лучше, чем search for rivals. :)

2020-05-25 10:51 UTC, ocassio commented on server/modules/auth/ws-auth.service.ts
> +            Logger.debug(`Token is empty: ${e.message}. ID: ${socket.id}`);
Logger лучше инстанцировать отдельно, чтобы у него было понимание контекста:
```ts
private readonly logger = new Logger(WsAuthService.name);
```

2020-05-25 10:51 UTC, ocassio commented on server/modules/auth/ws-auth.service.ts
> +                `Token: ${socket.handshake.query.tokenSecretKey}. Payload: ${payload}`
Токен нельзя светить в логах, это чревато проблемами с безопасностью.

2020-05-25 10:51 UTC, ocassio commented on server/modules/auth/ws-auth.service.ts
> +                socket.handshake.query.tokenSecretKey,
Это не секретный ключ, это просто авторизационный токен.

2020-05-25 10:51 UTC, ocassio commented on server/modules/auth/ws-auth.service.ts
> +            return undefined;
undefined возвращать смысла нет, это стандартное поведение.

2020-05-25 10:51 UTC, ocassio commented on server/modules/auth/ws-auth.service.ts
> +        socket.emit("connection", "401");
Исходя из названия, это штатное отключение.  А внутри 401.

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/search.ts
> +export interface Search {
SearchService

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/search.ts
> +    ): Promise<RoomDto> | undefined;
Асинхронная функция всегда возвращает Promise, а вот результат уже может быть либо RoomDto, либо undefined.

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/modes/classic.service.ts
> +export class ClassicService implements Search {
ClassicSearchService

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/search-factory.service.ts
> +    searchForRivals(mode: GameModeEnum): Search {
1. SearchServiceFactory
2. Это не поиск противников, это получение сервиса для поиска.
3. Интерфейс в данном случае не особо нужен.

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/modes/classic.service.ts
> +    private mode: GameModeEnum = GameModeEnum.CLASSIC;
А где он используется?

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +        const room: RoomDto = await searchFactory.search(
Фабрика возвращает сервис, а сервис подбирает соперников.
Тут по факту все правильно, но с именами какая-то путаница.

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +    private idToClassicModeMapping = new Map<string, SearchDto>();
Не, смотри, тебе тут нужен полноценный маппинг по режимам, вроде такого:
```ts
interface SearchParticipant {
  socketId: string;
  data: SearchDto; // Это возможно стоит заинлайнить
}

const participants = new Map<GameModeEnum, SearchParticipant>();
```

Тогда логика по обработке становится довольно прямолинейной, практически без ветвлений.

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/modes/classic.service.ts
> +                await this.participantService.create(game, value.id);
Мне кажется, создание участников можно сразу в создание игры заложить, опциональным параметром.

2020-05-25 10:51 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +        const user: UserDAO = await this.wsAuthService.tokenCheck(socket);
Тут стоит либо объединить, т.е. дисконнект вызывать уже в рамках проверки, т.к. операция прям типовая, будет везде.
Либо, как минимум заменить tokenCheck, на getUser.

2020-05-25 11:32 UTC, fanikuk commented on server/modules/search-for-rivals/modes/classic.service.ts
> +    private mode: GameModeEnum = GameModeEnum.CLASSIC;
при создании игры

2020-05-26 07:59 UTC, ocassio requested changes

2020-05-26 07:59 UTC, ocassio commented on server/modules/auth/ws-auth.service.ts
> +            this.logger.debug(`Payload: ${payload}`);
Payload тоже обычно чувствительные данные содержит :)

2020-05-26 07:59 UTC, ocassio commented on server/modules/game/game.service.ts
> +        isPrivate?,
Тип.

2020-05-26 07:59 UTC, ocassio commented on server/modules/matchmaking/matchmaking.gateway.ts
> +            this.modeToParticipantsMapping.set(
1. classicModeParticipants тебе больше не нужны.
2. Условие тебе тоже здесь больше не нужно.

2020-05-26 07:59 UTC, ocassio commented on server/modules/search-for-rivals/search-for-rivals.gateway.ts
> +        const room: RoomDto = await searchFactory.search(
Еще актуально.

2020-05-26 10:27 UTC, ocassio requested changes

2020-05-26 10:27 UTC, ocassio commented on server/modules/matchmaking/matchmaking.gateway.ts
> +        );
А для чего заново сетить весь список? Тут же вот этого вполне достаточно:
```js
            this.modeToParticipantsMapping
                .get(req.gameMode)
                .set(socket.id.toString(), req)
```

2020-05-26 10:27 UTC, ocassio commented on server/modules/matchmaking/modes/classic-search.service.ts
> +    ): Promise<RoomDto> | undefined {
Это всегда Promise, который возвращает либо RoomDto, либо undefined.

2020-05-26 10:27 UTC, ocassio commented on server/modules/auth/ws-auth.service.ts
> +    async getUser(socket: Socket): Promise<UserDAO> | undefined {
Это всегда Promise, который возвращает либо UserDAO, либо undefined.

2020-05-26 10:51 UTC, ocassio approved these changes

2020-05-26 10:52 UTC, merged