feature/28-matchmaking-for-quick-game
ncedu-tlt/2019-ux-sea-battle pull request #30
Opened 2020-06-08 12:38 UTC by fanikuk

Closes #28

2020-06-09 06:40 UTC, ocassio requested changes

2020-06-09 06:40 UTC, ocassio commented on client/app/app-routing.module.ts
> +        component: MainMenuComponent
Меню у нас на главной странице должно быть.
И требовать авторизации.

2020-06-09 06:40 UTC, ocassio commented on client/app/app-routing.module.ts
> +        component: LoadingScreenComponent
Ну это все-таки не просто загрузка. Это поиск игры. Также требуется авторизация.

2020-06-09 06:40 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.component.ts
> +    ticks = 0;
Если нужен комментарий, то не стоит ли просто переименовать переменную?)

2020-06-09 06:40 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.component.ts
> +    ticks = 0;
И да, можно было просто использовать значение переменной `timer` напрямую, используя async pipe.

2020-06-09 06:40 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.component.ts
> +    providers: [LoadingScreenService]
Когда ты объявляешь провайдер на уровне компонента, то у тебя при создании нового экземпляра компонента создается новый экземпляр сервиса. Ты точно этого хотел добиться?

2020-06-09 06:40 UTC, ocassio commented on server/modules/game/game.service.ts
> +            throw new HttpException(
Немного неверный подход.
Ты выкидываешь HttpException, хотя работаешь на сервисном уровне и не можешь сказать, где именно будет использоваться этот метод. Причем вполне нормально с точки зрения потребителя запросить игру и увидеть, что такой нет. При этом он не всегда захочет выкидывать исключение, возможно, он просто изменит логику.

2020-06-09 06:40 UTC, ocassio commented on server/modules/game/game.service.ts
> +            throw new HttpException(
Аналогично.

2020-06-09 06:40 UTC, ocassio commented on server/modules/matchmaking/matchmaking.gateway.ts
> +            socket.emit("connection", user.id);
А зачем ему отправлять его же идентификатор? И вообще как-то отдельно нотифицировать?

2020-06-09 06:40 UTC, ocassio commented on server/modules/matchmaking/matchmaking.gateway.ts
> +        socket.emit("leave", socket.id);
Аналогично, ты оповещаешь самого пользователя о том, что он отключился. Но он это уже знает :)

2020-06-09 06:40 UTC, ocassio commented on server/modules/db/domain/participant.dao.ts
> +    game: GameDAO;
Вот игру может все-таки оставить ленивой? Например, для сценария, когда ты получаешь список игроков в игре, тебе не нужно для каждого из них снова загружать информацию об игре.

2020-06-09 06:40 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.service.ts
> +            return "Классика";
Чисто UI логика, маппинг лучше делать там же.

2020-06-09 06:40 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.component.ts
> +    isLoading = false;
А может быть другой расклад? Мы вроде всегда ищем, пока на этом экране находимся.

2020-06-09 06:40 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.component.ts
> +            id: this.userId,
Мы не должны явно передавать ID пользователя.
Во-первых, сервер его уже знает из токена. Во-вторых, ты дал возможность клиенту поставить в поиск другого игрока.

2020-06-09 06:40 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.component.ts
> +        this.timer = timer(0, 1000);
А почему ограничение до тысячи?

2020-06-09 06:40 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.component.ts
> +    onLeave(): void {
Старайся держать публичные методы до приватных. Обычно они являются точками входа, которые ищут в первую очередь. Лучше держать их под рукой.

2020-06-09 11:13 UTC, fanikuk commented on client/app/components/loading-screen/loading-screen.component.ts
> +        this.timer = timer(0, 1000);
Это же не ограничение, а кол-во тиков в период. Или я не правильно понял?

2020-06-09 11:15 UTC, ocassio commented on client/app/components/loading-screen/loading-screen.component.ts
> +        this.timer = timer(0, 1000);
Вопрос снят, не доглядел :)

2020-06-15 14:52 UTC, ocassio requested changes

2020-06-15 14:52 UTC, ocassio commented on client/app/services/token.service.ts
> +            new Date().getHours() + 1,
Если передавать сюда цифру, то он воспринимает это как количество дней. В твоем случае целесообразней передать Date.

2020-06-15 14:52 UTC, ocassio commented on server/modules/game/game-management.controller.ts
> +    async getGame(@Param("id") id): Promise<GameDto> {
Типы не забываем.

2020-06-15 14:52 UTC, ocassio commented on server/modules/game/game.service.ts
> +            throw new HttpException(
Еще актуально.

2020-06-15 14:52 UTC, ocassio commented on client/app/services/ws/matchmaking.service.ts
> +        return this.socket.fromEvent<string>("leave");
А где оно на сервере выкидывается?
И мне кажется, что просто `leave` недостаточно точно описывает ситуацию с протухшей авторизацией.

2020-06-15 15:58 UTC, ocassio approved these changes

2020-06-15 15:58 UTC, merged