WIP: 1 // registration new user & auth
ncedu-tlt/2019-ux-sea-battle pull request #8
Opened 2020-03-20 18:22 UTC by awpogodin

2020-03-20 18:26 UTC, awpogodin commented
Пароли не хэшируются, логин не работает (всегда выдает UnauthorizedException)

2020-03-21 20:10 UTC, awpogodin commented
Fixed

2020-03-22 09:25 UTC, ocassio requested changes

2020-03-22 09:25 UTC, ocassio commented on .env.example
> +SECRET_KEY="secret"
Хотелось бы, чтобы переменная имела более выразительное имя. Для его используется этот секрет? В теории, секрет это любое значение, которое не стоит светить.

2020-03-22 09:25 UTC, ocassio commented on common/dto/auth.dto.ts
> +export interface RegisterDTO {
1. Одна сущность - один файл.
2. Если это тело запроса, то уточняй этот факт в названии.

2020-03-22 09:25 UTC, ocassio commented on common/dto/user.dto.ts
> +    nickname: string;
1. В каком сценарии мы можем отправлять пароль?
2. Мы вроде проговаривали, что почта - вещь опциональная. Для пользователей, которые вошли через соц. сети ее может не быть.

2020-03-22 09:25 UTC, ocassio commented on common/interfaces/payload.interface.ts
> +export interface Payload {
Не надо акцентироваться на реализации, надо делать акцент на то, что это такое. Всем все равно, что это инетрфейс, это и так из объявления ясно. У нас же это модель. Более того, payload чего это? Из названия не ясно совершенно.

Далее, опциональные поля `iat` и `expiresIn` намекают на то, что эта модель используется в нескольких различных сценариях. Соответственно, у нас должно быть по модели для каждого из них.

И еще, почему мы шлем `email`, если:
1. Это опциональная вещь.
2. Уникальным идентификаторов у нас служит id?

2020-03-22 09:25 UTC, ocassio commented on common/interfaces/token.interface.ts
> +export interface IToken {
1. Правила созданы не для того, чтобы их игнорить, а для того, чтобы им следовать. Префикс для интерфейсов принят в Microsoft сообществе. Ни в Angular, ни в Nest это является не считается хорошей практикой.
2. Снова интерфейс, а не DTO.
3. Почему модель называется токеном, хотя токен там содержится только в одном из полей?
4. Снова email.
5. Зачем там время выпуска? Еще и опциональное.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.controller.ts
> +    async login(@Body() loginDTO: LoginDTO): Promise<IToken> {
1. Зачем помечать метод как `async`, если ты не используешь `await`?
2. Именам переменных уже не обязательно добавлять постфикс с DTO, это лишний шум для внутренней логики.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.controller.ts
> +    async register(@Body() registerDTO: RegisterDTO): Promise<any> {
`any` позволительно использовать лишь в одном случае - когда у тебя реально может придти все, что угодно. Ты же сам формируешь ответ и можешь его однозначно типизировать.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.controller.ts
> +    protected(@Request() req): string {
1. Явно тестовый код. Убираем.
2. Так как мы будем авторизовывать пользователя исключительно по JWT, нет смысла делать отдельный  `JWTAuthGuard`. Можно прописать дефолтную стратегию и использовать коробочный `AuthGuard`. Это позволит нам в случае необходимости легко переключиться на другую стратегию.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.module.ts
> +const SECRET_KEY = process.env.SECRET_KEY || "secret";
1. Нужно использовать `ConfigService` для любой конфигурации.
2. Значение по умолчанию в данном случае задавать не безопасно, пользователь должен явно указать секретный ключ самостоятельно. Иначе это дыра в безопасности.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +        private readonly jwtService: JwtService
Если уж решил использовать `readonly`, то используй везде.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +        return await this.usersService.findByEmail(payload.email);
1. Почему у тебя функция `validate` ищет пользователя и возвращает его? Это запутает пользователя.
2. async/await в данном случае не имеют смысла. Ты и так получаешь Promise, просто верни его и все.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +            throw new HttpException("Invalid email", HttpStatus.UNAUTHORIZED);
Разделение ошибки авторизации на email/пароль - дыра в безопасности. Таким образом злоумышленник сможет собрать БД зарегистрированных пользователей.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +                expiresIn: "1h"
Вот эта вещь прям проситься в конфигурацию.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +                iat: Number(Date.now())
`iat` там и без тебя проставят. :)
Тебя интересует исключительно полезная нагрузка.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +            message: "User created"
Такие сообщение никогда слать не стоит. У тебя API, а не UI. Используем только коды.

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/auth.service.ts
> +        };
Тип?

2020-03-22 09:25 UTC, ocassio commented on server/modules/auth/passport/jwt.strategy.ts
> +const SECRET_KEY = process.env.SECRET_KEY || "secret";
ConfigService

2020-03-22 09:25 UTC, ocassio commented on server/modules/users/users.service.ts
> +        return await this.usersRepository.findOne({
1. Снова async/await.
2. `findOne` умеет принимать просто id.

2020-03-22 09:25 UTC, ocassio commented on common/dto/player.dto.ts
> +    name?: string;
Т.е. ты просто решил, что раз у тебя нет поля с таким же именем, то можно сломать функционал? :)
Раз пересадил на своих юзеров, то будь добр сделать так, чтобы оно по прежнему работало как раньше.

2020-03-22 09:25 UTC, ocassio commented on .env.example
> +DATABASE_URL=postgres://postgres:postgres@localhost:5432/dbname
Задумка с примером хорошая. Советую завести wiki страничку с описанием и примерами всех переменных окружения.

2020-03-22 09:25 UTC, ocassio commented on .env.example
> +DATABASE_URL=postgres://postgres:postgres@localhost:5432/dbname
И еще просьба добавлять обязательные новые переменные окружения в app.json. Выглядеть должно как-то так:
```json
"env": {
  "SECRET_KEY": {
    "required": true 
  }
},
```

2020-03-22 10:37 UTC, awpogodin commented on common/dto/auth.dto.ts
> +export interface RegisterDTO {
RegisterBodyDTO?

2020-03-22 10:41 UTC, ocassio commented on common/dto/auth.dto.ts
> +export interface RegisterDTO {
RegistrationRequestDTO

2020-03-22 11:31 UTC, awpogodin commented on common/dto/player.dto.ts
> +    name?: string;
У нас же нет Player'ов )

2020-03-22 11:33 UTC, ocassio commented on common/dto/player.dto.ts
> +    name?: string;
API есть? Есть. Тут либо убирать, либо поддерживать в рабочем состоянии. А частично сломать и оставить - не дело.

2020-03-23 13:18 UTC, ocassio requested changes

2020-03-23 13:18 UTC, ocassio commented on .env.example
> +DATABASE_URL=postgres://postgres:postgres@localhost:5432/dbname
Было два ключевых слова "новые" и "обязательные". :)

- PORT (не PORT_SERVER) - предоставляется самим Heroku и не должен прописываться в конфиге. Более того, приложение обязано использовать его, так как порты там определяются динамически. Твое изменение сломало деплоймент (на который неплохо было бы смотреть после коммита).
- DATABASE_URL - аналогично в динамике предоставляется самим Heroku не должно указываться в конфиге.

2020-03-23 13:18 UTC, ocassio commented on common/dto/player.dto.ts
> +    nickname: string;
API по прежнему сломан. Клиент завязан именно на name. Ты же без объявления войны изменил контракт.

2020-03-23 13:18 UTC, ocassio commented on common/models/payload.model.ts
> +export interface PayloadModel {
1. Уже поднимался вопрос. Payload чего?
2. sub и iat заполняются самим фреймворком, нас интересует исключительно полезная нагрузка.

2020-03-23 13:18 UTC, ocassio commented on server/app.module.ts
> -        PlayersModule
А почему модуль со старым API выключен? Клиент по прежнему его ожидает. API внезапно пропал.

2020-03-23 13:18 UTC, ocassio commented on server/config/main.config.ts
> +    secretOrKey: process.env.TOKEN_SECRET_KEY
Секрет или ключ? Не понятно.

2020-03-23 13:18 UTC, ocassio commented on server/main.ts
> +    const port = configService.get("port") || 3000;
Значение по-умолчанию стоит задавать в самом конфиге, а не по месту использования.

2020-03-23 13:18 UTC, ocassio commented on server/modules/users/users.controller.ts
> +            email: user.email || ""
Поле опциональное, зачем нам слать его название с пустой строкой?

2020-03-27 06:43 UTC, ocassio requested changes

2020-03-27 06:43 UTC, ocassio commented on app.json
> +        "TOKEN_EXPIRES_IN": {
Он опциональный. Убираем.

2020-03-27 06:43 UTC, ocassio commented on server/modules/users/users.service.ts
> +    async create(user: RegisterRequestDTO): Promise<UserDAO> {
Снова async/await лишние.

2020-03-27 06:43 UTC, ocassio commented on client/app/services/api/players.api.service.ts
>  export class PlayersApiService {
А почему у тебя PlayersApiService оперирует пользователями?

2020-03-27 06:43 UTC, ocassio commented on server/modules/db/domain/user.dao.ts
> +    email: string;
Зачем нам дефолт в виде пустой строки? Пусть null и будет.
И nullable тип не забываем, причем на пароль тоже.

2020-03-27 12:39 UTC, ocassio approved these changes

2020-03-27 12:41 UTC, merged